# Generated by Django 4.2.4 on 2023-08-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('url', models.CharField(max_length=150, unique=True)),
                ('longitude', models.FloatField(unique=True)),
                ('latitude', models.FloatField(unique=True)),
            ],
        ),
    ]
