# Generated by Django 4.2.4 on 2023-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, unique=True)),
                ('last_name', models.CharField(max_length=120, unique=True)),
                ('age', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['first_name', 'last_name', 'age'], name='api_crimina_first_n_d983bc_idx')],
            },
        ),
    ]
